# Generated by Django 5.2.1 on 2026-01-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_en", models.CharField(max_length=200)),
                ("title_sr", models.CharField(blank=True, max_length=200)),
                ("title_de", models.CharField(blank=True, max_length=200)),
                ("summary_en", models.TextField(blank=True)),
                ("summary_sr", models.TextField(blank=True)),
                ("summary_de", models.TextField(blank=True)),
                ("content_en", models.TextField()),
                ("content_sr", models.TextField(blank=True)),
                ("content_de", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="blog/")),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("is_published", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
