# Generated by Django 5.2.1 on 2025-06-03 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0002_quizattempt"),
    ]

    operations = [
        migrations.CreateModel(
            name="SortingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("item", models.CharField(max_length=100)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sorting_pairs",
                        to="quizzes.quiz",
                    ),
                ),
            ],
        ),
    ]
