# Generated by Django 5.2.1 on 2025-06-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0003_sortingpair"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="image_mode",
            field=models.CharField(
                choices=[
                    ("word", "Image per Word"),
                    ("category", "Image per Category"),
                ],
                default="word",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sortingpair",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="sorting_images/"),
        ),
    ]
