# Generated by Django 5.2.1 on 2025-06-05 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0005_visualquiz_visualquizquestion_visualquizoption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="quiz_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("fill_blank", "Fill in the Blank"),
                    ("drag_drop", "Drag and Drop"),
                    ("visual", "Visual Quiz"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="visualquizquestion",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visual_questions",
                to="quizzes.quiz",
            ),
        ),
    ]
