# Generated by Django 5.2.1 on 2025-06-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0006_alter_quiz_quiz_type_alter_visualquizquestion_quiz"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VisualQuiz",
        ),
    ]
