# Generated by Django 5.2.1 on 2025-06-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0007_delete_visualquiz"),
    ]

    operations = [
        migrations.CreateModel(
            name="SortingLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="label_images/"),
                ),
            ],
        ),
    ]
