# Generated by Django 5.2.1 on 2025-06-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0008_sortinglabel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SortingLabel",
        ),
    ]
