# Generated by Django 5.2.1 on 2025-06-09 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0010_label_alter_sortingpair_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sortingpair",
            name="label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quizzes.label",
            ),
        ),
    ]
