# Generated by Django 5.2.1 on 2025-06-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0013_alter_sortingpair_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sortingpair",
            name="label",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Label",
        ),
    ]
