# Generated by Django 5.2.1 on 2025-06-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0014_alter_sortingpair_label_delete_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("image", models.ImageField(upload_to="label_backgrounds/")),
            ],
        ),
    ]
