# Generated by Django 5.2.1 on 2025-06-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0015_labelimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LabelImage",
        ),
    ]
