# Generated by Django 5.2.1 on 2025-06-10 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0016_delete_labelimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="quiz_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("fill_blank", "Fill in the Blank"),
                    ("drag_drop", "Drag and Drop"),
                    ("visual", "Visual Quiz"),
                    ("matching", "Matching Quiz"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="MatchingPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="matching_game_images/")),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_pairs",
                        to="quizzes.quiz",
                    ),
                ),
            ],
        ),
    ]
