# Generated by Django 5.2.1 on 2025-06-10 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0017_alter_quiz_quiz_type_matchingpair"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchingGame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="matching_game/")),
                ("correct_word", models.CharField(max_length=255)),
                (
                    "distractor1",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "distractor2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matching_items",
                        to="quizzes.quiz",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MatchingPair",
        ),
    ]
