# Generated by Django 5.2.1 on 2025-06-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0018_matchinggame_delete_matchingpair"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchinggame",
            name="correct_word",
        ),
        migrations.AddField(
            model_name="matchinggame",
            name="full_word",
            field=models.CharField(
                blank=True,
                help_text="Full correct word, e.g., 'cat'",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="matchinggame",
            name="missing_index",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Index of missing letter, e.g., 1 for 'c_t'",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="matchinggame",
            name="distractor1",
            field=models.CharField(
                blank=True, help_text="Wrong letter option 1", max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="matchinggame",
            name="distractor2",
            field=models.CharField(
                blank=True, help_text="Wrong letter option 2", max_length=1, null=True
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="quiz_type",
            field=models.CharField(
                choices=[
                    ("multiple_choice", "Multiple Choice"),
                    ("fill_blank", "Fill in the Blank"),
                    ("drag_drop", "Drag and Drop"),
                    ("visual", "Visual Quiz"),
                    ("matching", "Spelling Quiz"),
                ],
                max_length=50,
            ),
        ),
    ]
