# Generated by Django 5.2.1 on 2025-07-04 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_lesson_video_file"),
        ("quizzes", "0019_remove_matchinggame_correct_word_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quizzes",
                to="lessons.lesson",
            ),
        ),
    ]
