# Generated by Django 5.2.1 on 2025-07-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0020_quiz_lesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="image_mode",
        ),
        migrations.AddField(
            model_name="quiz",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="quiz_covers/"),
        ),
    ]
