# Generated by Django 5.2.1 on 2026-01-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0022_alter_quiz_quiz_type_audioquizquestion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visualquizoption",
            name="text",
        ),
        migrations.RemoveField(
            model_name="visualquizquestion",
            name="correct_answer",
        ),
        migrations.RemoveField(
            model_name="visualquizquestion",
            name="image",
        ),
        migrations.AddField(
            model_name="visualquizoption",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="visual_quiz_options/"
            ),
        ),
        migrations.AddField(
            model_name="visualquizoption",
            name="is_correct",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="visualquizquestion",
            name="question_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="visual_quiz_questions/"
            ),
        ),
        migrations.AddField(
            model_name="visualquizquestion",
            name="question_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
