# Generated by Django 5.2.1 on 2025-06-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="video_file",
            field=models.FileField(blank=True, null=True, upload_to="lessons/videos/"),
        ),
    ]
