# Generated by Django 5.2.1 on 2025-09-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_lesson_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="age_group",
            field=models.CharField(
                choices=[("4-5", "4–5 years"), ("6-7", "6–7 years")],
                default="4-5",
                max_length=10,
            ),
        ),
    ]
