# Generated by Django 5.2.1 on 2025-09-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_lesson_age_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["category__order", "order", "created_at"]},
        ),
        migrations.AlterModelOptions(
            name="lessoncategory",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="lesson",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Control the flow of lessons for each age group"
            ),
        ),
        migrations.AddField(
            model_name="lessoncategory",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Control the order of categories (e.g., Spelling first)",
            ),
        ),
    ]
