# Generated by Django 5.2.1 on 2025-12-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0006_contactmessage_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="description_de",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description (German)"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="description_sr",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description (Serbian)"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="title_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title (German)"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="title_sr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Title (Serbian)"
            ),
        ),
    ]
