# Generated by Django 5.2.1 on 2026-01-21 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0007_lesson_description_de_lesson_description_sr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Optional short video for this block",
                        null=True,
                        upload_to="lesson_videos/",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[("explain", "Explain"), ("story", "Story")],
                        default="explain",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Playback order inside the lesson"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="lessons.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
