# Generated by Django 5.2.1 on 2026-01-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0008_lessonblock"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonblock",
            name="title_de",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="lessonblock",
            name="title_sr",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
