# Generated by Django 5.2.1 on 2025-09-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0002_worksheet_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="worksheet",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="resources_images/"
            ),
        ),
    ]
